resources:
  - aws-load-balancer-controller.yaml
  - external-secrets.yaml
  - external-dns.yaml
  - keda.yaml
  - kube-prometheus-stack.yaml
  - namespaces.yaml
  - storageclass.yaml
  - yace.yaml
  - cluster-autoscaler.yaml