apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: ticket-gateway-config
  namespace: ticketing
spec:
  scheme: internet-facing
  tags:
    Environment: prod
    Team: team5
    Project: ticket-platform
    Owner: team5
