apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    helm:
      values: |
        clusterName: team5-dev-eks
        region: ap-northeast-2
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
        enableGatewayAPI: true
