apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-addons-dev
  namespace: argocd
spec:
  project: team5-project
  source:
    repoURL: https://github.com/CLD-05/team5-ticket-config.git
    targetRevision: main
    path: system-addons/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
