apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-app-prod
  namespace: argocd
spec:
  project: team5-project
  source:
    repoURL: https://github.com/CLD-05/team5-ticket-config.git
    targetRevision: develop
    path: apps/ticket-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
