apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team5-project
  namespace: argocd
spec:
  description: team5 ticket-platform gitops project
  sourceRepos:
    - https://github.com/CLD-05/team5-ticket-config.git
  destinations:
    - namespace: ticketing
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: keda
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
