apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-addons
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/CLD-05/team5-ticket-config.git
    targetRevision: develop
    path: system-addons

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
