apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ticket-app-secret
  namespace: ticketing
  labels:
    app: booking
    app.kubernetes.io/name: ticket-service
    app.kubernetes.io/part-of: team5-ticket
spec:
  refreshInterval: 1h

  # External Secrets 담당자가 생성한 ClusterSecretStore 이름과 맞아야 됨
  # 이름이 다를경우 수정필요
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: ticket-app-secret
    creationPolicy: Owner

  # Terraform modules/secrets가 생성한 AWS Secrets Manager 값을 앱 환경변수로 동기화
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: team5/dev/ticket-app
        property: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: team5/dev/ticket-app
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: team5/dev/ticket-app
        property: SPRING_DATASOURCE_PASSWORD
    - secretKey: SPRING_DATA_REDIS_HOST
      remoteRef:
        key: team5/dev/ticket-app
        property: SPRING_DATA_REDIS_HOST
    - secretKey: SPRING_DATA_REDIS_PORT
      remoteRef:
        key: team5/dev/ticket-app
        property: SPRING_DATA_REDIS_PORT
    - secretKey: AWS_SQS_BOOKING_QUEUE_URL
      remoteRef:
        key: team5/dev/ticket-app
        property: AWS_SQS_BOOKING_QUEUE_URL
    - secretKey: AWS_SQS_BOOKING_QUEUE_ARN
      remoteRef:
        key: team5/dev/ticket-app
        property: AWS_SQS_BOOKING_QUEUE_ARN
    - secretKey: JWT_SECRET
      remoteRef:
        key: team5/dev/ticket-app
        property: JWT_SECRET
